apiVersion: apps/v1
kind: Deployment

metadata:
  name: smart-exam-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: smart-exam

  template:
    metadata:
      labels:
        app: smart-exam

    spec:
      containers:
        - name: smart-exam

          image: aman1240/smart-exam-system:latest

          ports:
            - containerPort: 3000
