name: CI Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Next.js App
        run: pnpm build
        
      - name: Build Next.js
        run: pnpm build
        env:
          MONGODB_URI: mongodb+srv://aman:aman@cluster0.vmv97za.mongodb.net/
          CLERK_SECRET_KEY: sk_test_TA6oroMUohxv3gT7QUC5SG8qqncRwVv1QOauCySzqn
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_Zmlyc3QtaGFkZG9jay02NC5jbGVyay5hY2NvdW50cy5kZXYk
          ADMIN_EMAIL: mca-reg202527223@timscdrmumbai.in 
